<?php
    if (isset($_SESSION['user'])) {
        header("Location: ?page=dashboard");
        exit;
    }
    echo '<h1>Login / Register</h1>';
    echo '<div>';
    echo '<div class="tab-container">';
    echo '<span class="tab active" id="tab-login" onclick="showTab(\'login\')">Login</span>';
    echo '<span class="tab" id="tab-register" onclick="showTab(\'register\')">Register</span>';
    echo '</div>';
    echo '<div id="login-form">';
    echo '<form action="?page=login_process&type=login" method="POST">';
    echo '<div class="form-group">';
    echo '<label for="login_email">Email</label>';
    echo '<input type="email" name="email" id="login_email" class="form-control" required>';
    echo '</div>';
    echo '<div class="form-group">';
    echo '<label for="login_password">Password</label>';
    echo '<input type="password" name="password" id="login_password" class="form-control" required>';
    echo '</div>';
    echo '<button type="submit" class="btn btn-primary">Login</button>';
    echo '</form>';
    echo '</div>';
    echo '<div id="register-form" style="display:none;">';
    echo '<form action="?page=login_process&type=register" method="POST">';
    echo '<div class="form-group">';
    echo '<label for="reg_fname">First Name</label>';
    echo '<input type="text" name="fname" id="reg_fname" class="form-control" required>';
    echo '</div>';
    echo '<div class="form-group">';
    echo '<label for="reg_mname">Middle Name</label>';
    echo '<input type="text" name="mname" id="reg_mname" class="form-control">';
    echo '</div>';
    echo '<div class="form-group">';
    echo '<label for="reg_lname">Last Name</label>';
    echo '<input type="text" name="lname" id="reg_lname" class="form-control" required>';
    echo '</div>';
    echo '<div class="form-group">';
    echo '<label for="reg_email">Email</label>';
    echo '<input type="email" name="email" id="reg_email" class="form-control" required>';
    echo '</div>';
    echo '<div class="form-group">';
    echo '<label for="reg_password">Password</label>';
    echo '<input type="password" name="password" id="reg_password" class="form-control" required>';
    echo '</div>';
    echo '<div class="form-group">';
    echo '<label for="reg_role">Role</label>';
    echo '<select name="role" id="reg_role" class="form-control" required>';
    echo '<option value="Donor">Donor</option>';
    echo '<option value="Campaigner">Campaigner</option>';
    echo '</select>';
    echo '</div>';
    echo '<div class="form-group">';
    echo '<label for="reg_wallet">Wallet Address</label>';
    echo '<input type="text" name="wallet" id="reg_wallet" class="form-control" required>';
    echo '<button type="button" id="connectWalletRegister" class="btn btn-secondary mt-2">Connect Wallet via MetaMask</button>';
    echo '</div>';
    echo '<button type="submit" class="btn btn-primary">Register</button>';
    echo '</form>';
    echo '<script>';
    echo 'async function connectWalletRegister(){';
    echo 'if (typeof window.ethereum !== \'undefined\') {';
    echo 'window.web3 = new Web3(window.ethereum);';
    echo 'try {';
    echo 'const accounts = await window.ethereum.request({ method: \'eth_requestAccounts\' });';
    echo 'document.getElementById("reg_wallet").value = accounts[0];';
    echo 'alert(\'Wallet connected: \' + accounts[0]);';
    echo '} catch (error) {';
    echo 'alert(\'Wallet connection failed: \' + error.message);';
    echo '}';
    echo '} else {';
    echo 'alert(\'Please install MetaMask\');';
    echo '}';
    echo '}';
    echo 'document.getElementById("connectWalletRegister").addEventListener("click", connectWalletRegister);';
    echo '</script>';
    echo '</div>';
    echo '</div>';
    echo '<script>';
    echo 'function showTab(tab){';
    echo 'if (tab === \'login\') {';
    echo 'document.getElementById(\'login-form\').style.display = \'block\';';
    echo 'document.getElementById(\'register-form\').style.display = \'none\';';
    echo 'document.getElementById(\'tab-login\').classList.add(\'active\');';
    echo 'document.getElementById(\'tab-register\').classList.remove(\'active\');';
    echo '} else {';
    echo 'document.getElementById(\'login-form\').style.display = \'none\';';
    echo 'document.getElementById(\'register-form\').style.display = \'block\';';
    echo 'document.getElementById(\'tab-register\').classList.add(\'active\');';
    echo 'document.getElementById(\'tab-login\').classList.remove(\'active\');';
    echo '}';
    echo '}';
    echo '</script>';
?>